### ISSUE TITLE
Memory plugin causes divide-by-zero error with no swap

### ISSUE THREAD

**Issue by mkf** [XANi/uberstatus#5]

**Comment by XANi** [comment]
Could you paste error you're getting, kernel version and how your `/proc/meminfo` looks like?

**Comment by mkf** [comment]
``` yaml
# vim: set ft=yaml syntax=yaml
---
plugins:
#    - name: example
#      plugin: example
    - name: volume
      plugin: i3blocks
      config:
        prefix: "VOL "
        command: /usr/lib/i3blocks/volume
        interval: 1001
        signal: 10
#    - name: memory
#      plugin: memory
#      config:
#        interval: 1001
#        prefix: "MEM "
    - name: network
      instance: enp4s1
      plugin: network
      config:
        iface: enp4s1
    - name: cpu
      plugin: cpu
      config:
        prefix: "CPU "
        interval: 500
    - name: clock
      plugin: clock
      config:
        long_format: "  Mon 2006-01-02 15:04:05  "
        short_format: 15:04
        interval: 100
```

```
 mf  ~  uberstatus 
{"version":1,"click_events":true}18:10:50.646 config↛LoadConfig: WARN 001 /home/mf/.config/uberstatus/uberstatus.conf
18:10:50.647 plugin↛NewPlugin: WARN 002 command: /usr/lib/i3blocks/volume
interval: 1001
prefix: 'VOL '
signal: 10
18:10:50.647 plugin↛NewPlugin: WARN 003 interval: 1001
prefix: 'MEM '
18:10:50.647 plugin↛NewPlugin: WARN 005 iface: enp4s1
18:10:50.647 i3blocks↛loadConfig: WARN 004 t: prefix VOL 
18:10:50.647 plugin↛NewPlugin: WARN 007 interval: 500
prefix: 'CPU '
18:10:50.647 i3blocks↛loadConfig: WARN 006 t: command /usr/lib/i3blocks/volume
18:10:50.647 plugin↛NewPlugin: WARN 009 interval: 100
long_format: '  Mon 2006-01-02 15:04:05  '
short_format: "15:04"
18:10:50.647 i3blocks↛loadConfig: WARN 008 unknown config key: [signal]
[
18:10:50.647 clock↛loadConfig: WARN 00b t: long_format
18:10:50.647 network↛loadConfig: WARN 00a -- iface enp4s1--
18:10:50.647 clock↛loadConfig: WARN 00c t: short_format
panic: runtime error: integer divide by zero

goroutine 9 [running]:
panic(0x7767e0, 0xc42000c170)
    /usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/XANi/uberstatus/plugin/memory.(*state).updatePeriodic(0xc42019aaf8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/mf/gopath/src/github.com/XANi/uberstatus/plugin/memory/memory.go:69 +0x750
github.com/XANi/uberstatus/plugin/memory.Run(0xc42000dba8, 0x6, 0x0, 0x0, 0xc420134690, 0xc42014e720, 0xc42014e780, 0xc42005bdc0)
    /home/mf/gopath/src/github.com/XANi/uberstatus/plugin/memory/memory.go:31 +0x9f
created by github.com/XANi/uberstatus/plugin.NewPlugin
    /home/mf/gopath/src/github.com/XANi/uberstatus/plugin/plugin.go:53 +0x3e6
 mf  ~  2  uname -a
Linux tichy 4.8.6-1-ARCH #1 SMP PREEMPT Mon Oct 31 18:51:30 CET 2016 x86_64 GNU/Linux
 mf  ~  
```

`/proc/meminfo`: 

```
MemTotal:       16307048 kB
MemFree:        12421424 kB
MemAvailable:   13500216 kB
Buffers:           33524 kB
Cached:          1328184 kB
SwapCached:            0 kB
Active:          2549636 kB
Inactive:         872992 kB
Active(anon):    2065368 kB
Inactive(anon):    80116 kB
Active(file):     484268 kB
Inactive(file):   792876 kB
Unevictable:          48 kB
Mlocked:              48 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:              1768 kB
Writeback:             0 kB
AnonPages:       2038048 kB
Mapped:           532564 kB
Shmem:             84576 kB
Slab:             230760 kB
SReclaimable:     108736 kB
SUnreclaim:       122024 kB
KernelStack:       50208 kB
PageTables:        62868 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     8153524 kB
Committed_AS:   10076340 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:    264192 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      363732 kB
DirectMap2M:    16283648 kB
```

Oh, I just realized that it is probably because I don't have any swap at the moment — just had no disk space and temporarily deleted the swap file :)

**Comment by XANi** [comment]
Try now, should work

**Comment by mkf** [comment]
I confirm, it works now. Thanks :)
